version: "3.8"

services:

  db:
    image: postgres:15
    container_name: norafit-db
    environment:
      POSTGRES_DB: norafit
      POSTGRES_USER: norafit_user
      POSTGRES_PASSWORD: norafit_pass
    ports:
      - "5432:5432"
    networks:
      - norafit-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: norafit-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/norafit
      SPRING_DATASOURCE_USERNAME: norafit_user
      SPRING_DATASOURCE_PASSWORD: norafit_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - norafit-network

networks:
  norafit-network:
    driver: bridge

volumes:
  postgres_data:
