spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.application.name=norafit
 
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.cpsoknlsbxrnawbewtwg
spring.datasource.password=gy57zkmX7uvAjv
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
 
twilio.account-sid=ACf06f5cc5f42801e0d8d7324ccd972a85
twilio.auth-token=e78af5f41ebbb9f3ed13d8562fae5ce0
twilio.phone-number=+18634561952
