name: validarInvest

on:
  workflow_dispatch:
    inputs:
      objetivo:
        description: "Objetivo del día"
        required: true
        default: "Avanzar en la integración de los métodos de actualización en el sistema y comenzar el desarrollo del frontend en Flutter."
      reunion:
        description: "Resumen de la reunión"
        required: true
        default: "Durante la reunión se trabajó en la integración de los métodos updateWeight y updateRepetitions. Se inició el desarrollo del frontend en Flutter, implementando la pantalla de bienvenida con el logo de NoraFit y las opciones principales de acceso. Se revisó que la estructura visual fuera coherente con el diseño planteado en los mockups."
      dudas:
        description: "Dudas"
        required: true
        default: "No hay dudas."

permissions:
  contents: read
  issues: write

jobs:
  crear-issue-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Crear issue daily
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FECHA=$(TZ=America/Bogota date +"%Y-%m-%d")
          TITULO="[Daily] $FECHA"

          gh issue create \
            --title "$TITULO" \
            --label "daily" \
            --body "## Objetivo
          ${{ inputs.objetivo }}

          ## Reunión
          ${{ inputs.reunion }}

          ## Dudas
          ${{ inputs.dudas }}"
